### ISSUE TITLE
Fix Travis CI build failures for pypy-5.3.1

### ISSUE THREAD

**Issue by aayush26** [aayush26/pirant#19]
Error:
```
 Downloading cryptography-2.1.1.tar.gz (441kB)

100% |████████████████████████████████| 450kB 2.3MB/s

Complete output from command python setup.py egg_info:

error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'

----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0R7v1L/cryptography/
```
Environment details:
```
$ python --version

Python 2.7.10 (7e8df3df9641, Jun 14 2016, 13:58:02)

[PyPy 5.3.1 with GCC 4.8.2]

$ pip --version

pip 8.1.2 from /home/travis/virtualenv/pypy-5.3.1/site-packages (python 2.7)
```

**Comment by PseudoAj** [comment]
Hey @aayush26 , this looks like an issue with travis supporting pypy `pypy-5.3.1`. I guess we can add a bash command to install and test it out. I want to give it a shot.

**Comment by aayush26** [comment]
@PseudoAj You can try to update the setuptools versions.
I was discussing the error here: https://github.com/pyca/cryptography/issues/3987 [ last 3 comments ]
To update setuptools for Travis CI, this SO link can be helpful: https://stackoverflow.com/questions/24714507/how-to-update-setuptools-on-tox-during-travis-build
All the best. This may or may not resolve this issue.

**Comment by PseudoAj** [comment]
This should fix the issue: https://github.com/aayush26/pirant/pull/25

**Comment by aayush26** [comment]
@PseudoAj Thanks for the contribution and fixing this up. A major fix.
